// Code generated by "stringer -type=ConnectionType"; DO NOT EDIT.

package visca

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[unknown-0]
	_ = x[TCP-1]
	_ = x[UDP-2]
	_ = x[CharDev-3]
	_ = x[Unix-4]
	_ = x[sentinel-5]
}

const _ConnectionType_name = "unknownTCPUDPCharDevUnixsentinel"

var _ConnectionType_index = [...]uint8{0, 7, 10, 13, 20, 24, 32}

func (i ConnectionType) String() string {
	if i < 0 || i >= ConnectionType(len(_ConnectionType_index)-1) {
		return "ConnectionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConnectionType_name[_ConnectionType_index[i]:_ConnectionType_index[i+1]]
}
