// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package visca

import mock "github.com/stretchr/testify/mock"

// MockConnection is an autogenerated mock type for the Connection type
type MockConnection struct {
	mock.Mock
}

// Send provides a mock function with given fields: _a0
func (_m *MockConnection) Send(_a0 *Packet) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*Packet) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetReceiveQueue provides a mock function with given fields: _a0
func (_m *MockConnection) SetReceiveQueue(_a0 chan *Packet) {
	_m.Called(_a0)
}

// Start provides a mock function with given fields:
func (_m *MockConnection) Start() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stop provides a mock function with given fields:
func (_m *MockConnection) Stop() {
	_m.Called()
}
